### ISSUE TITLE
Clarification of model

### ISSUE THREAD

**Issue by RutgerLubbers** [PatrickDiallo23/Automatic-Timetable-Generation-System#1]
Hi Patrick,

Thanks for this code. The code itself is not 100% useable, for instance the paid version of timefold is used. 

Further the student group entity is not entirely clear to me. What is the use of "year", "name", "student group" and "semi group" in this model?

Further there are a few code cleanups that could help, for instance removal of 'public' in interfaces, update of libraries and removal of deprecations, or introduction of a few enumerations.

I could take this up if you would like.

**Comment by PatrickDiallo23** [comment]
Hi Rutger,

Thank you for raising the issue.

This project is a prototype for generating a timetable for Polytechnic University of Bucharest. It was implemented for research/development reasons. Indeed, the paid version of Timefold is used, but you can use version 1.9.0 of Timefold to test its capabilities (multithreading solver included) and see how Timefold would behave in a complex scenario. Note that the paid version can be used only in development.

The model is designed at the moment only for the Faculty of Automatic Control and Computer Science which requires a complex model. The students are divided into smaller groups by year, series, groups and semigroups. For example, Student A. is in year 3 (THIRD), series AB, group 333 AB, semigroup B.

I will clarify all details about this project in the future. At the moment, this project is used for research only, so it doesn't need any modifications. I will let you know if it is necessary to improve/modify the codebase. Thank you for your understanding.

If you have any questions, please don't hesitate to ask away.
